# Generated by Django 3.1 on 2021-05-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210510_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='GroupId',
            new_name='groupId',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='UserId',
            new_name='userId',
        ),
    ]
